[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/asdine/storm"
  version = "2.1.1"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  name = "github.com/gin-contrib/cors"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "gopkg.in/dgrijalva/jwt-go.v3"
  version = "3.2.0"

[[constraint]]
  name = "github.com/google/uuid"
  version = "1.0.0"
